// === ОСНОВНІ ФУНКЦІЇ ===
function startGame(v){document.getElementById('chooser').style.display='none';document.getElementById('game').classList.remove('game-hidden');if(v==='mobile')document.body.classList.add('mobile-version');else document.body.classList.remove('mobile-version');initGame()}
function initGame(){    
// === ЗМІННІ СТАНУ ===
let score=0,clickPower=1,autoRate=0,isPlaying=0,currentTrack=0,sessionStart=Date.now(),totalUpgradesBought=0,maxPerClick=1,prestigeMultiplier=1,totalReverbs=0,maxAutoRate=0,maxCombo=0,clickCloudTotal=0,lastClickTime=0,currentCombo=0,maxComboEver=0,comboTimeout=null,MAX_CLICK_INTERVAL=350,COMBO_THRESHOLD=5,isReverbActive=0,reverbHoldTimeout=null,clickMultiplier=1,buttons=[],prestigeThreshold=3600,currentPrestigeProgress=0; 
// === ОПТИМІЗАЦІЯ ДЛЯ МОБІЛЬНИХ (НЕ ВПЛИВАЄ НА ПК) ===
const m='ontouchstart'in window||navigator.maxTouchPoints>0;
if(m){
// ОНОВЛЕННЯ СТРІЛОК - ЗМЕНШЕНА ЧАСТОТА
const oh=updateClockHands;
let rafId, lastUpdate=0;
updateClockHands=()=>{    const now=Date.now();    if(now-lastUpdate>=50){        oh();        lastUpdate=now;    }    rafId=requestAnimationFrame(updateClockHands);};

// АВТО-КЛІКИ - ОПТИМІЗОВАНІ ІНТЕРВАЛИ
const ai=setInterval(()=>{const g=Math.round(autoRate*prestigeMultiplier);if(g>0){score+=g;clickCloudTotal+=g;if(score%100===0)updateScore();}if(Date.now()%3e3<100){updateStats();updateAchievements();}},1e3);

// СКІНИ - ЗМЕНШЕНА ЧАСТОТА ОНОВЛЕННЯ
let skinUpdateTimeout;
function debouncedUpdateSkins() {    clearTimeout(skinUpdateTimeout);    skinUpdateTimeout = setTimeout(updateSkinHighlights, 150);}
const sui = setInterval(debouncedUpdateSkins, 50);

// ПЛАВАЮЧІ ЧИСЛА - ОБМЕЖЕННЯ КІЛЬКОСТІ
let f=[];const osf=showFloating;showFloating=t=>{    if(f.length>=2){        f.forEach((o,i)=>{if(i<f.length-1&&o.parentNode)o.parentNode.removeChild(o);});        f=f.slice(-1); }
const e=d.createElement("div");e.textContent=t;e.style.cssText="position:absolute;right:10px;top:30px;color:#ffccd1;font-weight:700;opacity:1;transition:all 0.7s ease-out;font-size:14px;";clockWrapper.appendChild(e);f.push(e);
requestAnimationFrame(()=>{e.style.transform="translateX(40px) translateY(-50px)";e.style.opacity="0";});setTimeout(()=>{if(e.parentNode)e.parentNode.removeChild(e);f=f.filter(i=>i!==e);},700);};

// СПОВІЩЕННЯ - ОБМЕЖЕННЯ КІЛЬКОСТІ
let tc=0;const ot=showToast;showToast=t=>{if(tc>=2)return;tc++;ot(t);setTimeout(()=>{tc=Math.max(0,tc-1);},3e3);};

// РЕВЕРБ СИСТЕМА - ОПТИМІЗАЦІЯ ОНОВЛЕННЯ
const or=updateReverbClockHands;let lr=0;updateReverbClockHands=()=>{const n=Date.now();if(n-lr<50){requestAnimationFrame(updateReverbClockHands);return;}lr=n;or();};
                                                 
// СТАТИСТИКА - ЗМЕНШЕНА ЧАСТОТА ОНОВЛЕННЯ
const si=setInterval(()=>{if(autoRate>maxAutoRate)maxAutoRate=autoRate;if(maxComboEver>maxCombo)maxCombo=maxComboEver;},2e3);
}
// === ВИПРАВЛЕНА ОПТИМІЗАЦІЯ - ТІЛЬКИ ДЛЯ МОБІЛЬНИХ ===
const d=document,q=s=>d.querySelector(s),qa=s=>d.querySelectorAll(s),id=s=>d.getElementById(s),clock=id("clickableClock"),clockWrapper=id("clockWrapper"),comboBubble=id("comboBubble"),comboCount=id("comboCount"),clickCloudEl=id("clickCloud"),musicBtn=id("musicBtn"),prevTrack=id("prevTrack"),nextTrack=id("nextTrack"),player=id("player"),scoreText=id("score"),upgradesContainer=id("upgrades"),multipliersContainer=id("multipliers"),clickGainEl=id("clickGain"),cloudTotalEl=id("cloudTotal"),nowPlaying=id("nowPlaying"),realTimePlayedEl=id("realTimePlayed"),virtualTimeEl=id("virtualTime"),totalUpgradesEl=id("totalUpgrades"),maxPerClickEl=id("maxPerClick"),prestigeMultEl=id("prestigeMult"),reverbBtn=id("reverbBtn"),timeTunnel=id("timeTunnel"),worldTitle=id("worldTitle"),toastContainer=id("toastContainer"),reverbOverlay=id("reverbOverlay"),reverbClock=id("reverbClock"),reverbHint=id("reverbHint");

// === ОНОВЛЕННЯ ДАТИ ===
function updateDate(){id("currentDate").textContent=new Date().toLocaleDateString('uk-UA')}
updateDate();setInterval(updateDate,60000);

// === МУЗИКА ===
const trackNames=["Фонк №1","Фонк №2","Фонк №3","Фонк №4","Фонк №5","Фонк №6","Фонк №7"],tracks=["asphalt-menace.mp3","digital-overdrive.mp3","drift-phonk-phonk-music-2-434611.mp3","drift-phonk-phonk-music-432222.mp3","phonk-music-409064 (2).mp3","phonk-music-phonk-2025-432208.mp3","pixel-drift.mp3"].map(x=>`musicList/${x}`);
function loadTrack(i){player.src=tracks[i];nowPlaying.textContent=`Зараз: ${trackNames[i]}`;if(isPlaying)player.play();}
loadTrack(0);
player.addEventListener("ended",()=>{currentTrack=(currentTrack+1)%tracks.length;loadTrack(currentTrack);});
musicBtn.addEventListener("click",()=>{
if(!isPlaying){isPlaying=1;player.volume=0.45;player.play().catch(()=>{});musicBtn.textContent="⏸ Зупинити музику";}
else{isPlaying=0;player.pause();musicBtn.textContent="▶️ Включити музику";}});
prevTrack.onclick=()=>{currentTrack=(currentTrack-1+tracks.length)%tracks.length;loadTrack(currentTrack);};
nextTrack.onclick=()=>{currentTrack=(currentTrack+1)%tracks.length;loadTrack(currentTrack);};

// === ФОРМАТУВАННЯ ЧАСУ ===
function formatTime(s){s=Math.floor(s);const u=[{name:"століття",v:3153600000},{name:"десятиліття",v:315360000},{name:"рік",v:31536000},{name:"міс",v:2592000},{name:"дн",v:86400},{name:"год",v:3600},{name:"хв",v:60},{name:"сек",v:1}];let r=s,p=[];for(const x of u){const a=Math.floor(r/x.v);if(a>0){p.push(`${a} ${x.name}`);r%=x.v;}}return p.length?p.join(" "):`${s} сек`;}
let timeCache = {};
function memoizedFormatTime(s) {    if(timeCache[s]) return timeCache[s];    const result = formatTime(s);    if(Object.keys(timeCache).length > 50) timeCache = {};    return timeCache[s] = result;}

// === АПГРЕЙДИ ===
const upgrades=[{n:"Кліпати очима",c:1,l:0},{n:"Увімкнути телефон",c:8,l:0},{n:"Гортати стрічку",c:40,l:0},{n:"Мем-тур",c:200,l:0},{n:"Автоперегляд",c:1100,l:0},{n:"Підписка",c:6500,l:0},{n:"Серіал-марафон",c:40000,l:0},{n:"Робота з дедлайном",c:250000,l:0},{n:"Життєвий крінж",c:1600000,l:0},{n:"Discord-марафон",c:10000000,l:0},{n:"Reels до ранку",c:65000000,l:0},{n:"Філософські роздуми",c:400000000,l:0}];
function fib(n){if(n<=1)return n;let a=0,b=1;for(let i=2;i<=n;i++)[a,b]=[b,a+b];return b;}
upgrades.forEach((u,i)=>{const b=d.createElement("button");b.className="upgrade-btn";if(i>0)b.classList.add("hidden");b.addEventListener("click",()=>buyUpgrade(i));upgradesContainer.appendChild(b);buttons.push(b);u.up=function(){const f=fib(u.l+6),c=Math.floor(u.c*f*(i+1));b.innerHTML=`${u.n} (Lv.${u.l})<span>${formatTime(c)}</span>`;b.disabled=score<c;};u.getC=function(){return Math.floor(u.c*fib(u.l+6)*(i+1));};u.up();});
function revealNext(){const c=upgrades.filter(u=>u.l>0).length;if(buttons[c])buttons[c].classList.remove("hidden");}
function buyUpgrade(i){const u=upgrades[i],c=u.getC();if(score<c)return;score-=c;u.l++;totalUpgradesBought++;autoRate+=(i+1)*5*prestigeMultiplier;showToast(`Куплено: ${u.n} (Lv.${u.l}) ✅`);if(u.n==="Увімкнути телефон"){setTimeout(()=>{showPhoneLockScreen();},500);}if(u.n==="Гортати стрічку"){setTimeout(()=>{handleNewsFeedUpgrade();},300);}if(u.n==="Мем-тур"){setTimeout(()=>{showMeme();setTimeout(()=>{score+=1000;clickCloudTotal+=1000;showToast("Посмішка за смішний мем! 😂");updateScore();},1500);},300);}if(u.n==="Автоперегляд"){setTimeout(()=>{showAutoplay();},300);}if(u.n==="Підписка"){setTimeout(()=>{showSubscription();},300);}requestAnimationFrame(()=>{revealNext();u.up();updateAllButtons();updateScore();updateStats();updateAchievements();updatePrestigeProgress();});if(u.n==="Кліпати очима"){d.body.classList.remove("eye-blink");void d.body.offsetWidth;d.body.classList.add("eye-blink");setTimeout(()=>d.body.classList.remove("eye-blink"),1000);}}
function updateAllButtons(){upgrades.forEach(u=>u.up());multipliers.forEach(m=>m.up&&m.up());}

// === МНОЖНИКИ КЛІКУ ===
const multipliers=[{n:"Подвійний клік",c:5000,m:2,b:0},{n:"Потрійний клік",c:50000,m:3,b:0},{n:"x10 за клік",c:1000000,m:10,b:0},{n:"x50 за клік",c:20000000,m:50,b:0},{n:"x100 за клік",c:100000000,m:100,b:0}];
multipliers.forEach(m=>{const b=d.createElement("button");b.className="upgrade-btn multiplier-btn";function upB(){if(m.b){b.remove();return;}const a=score>=m.c;b.innerHTML=`${m.n}<span>${formatTime(m.c)}</span>`;b.disabled=!a;b.style.background=a?"":"#334155";b.style.opacity=a?"1":"0.5";}b.addEventListener("click",()=>{if(score<m.c||m.b)return;    requestAnimationFrame(()=>{        score-=m.c;m.b=1;clickMultiplier=m.m;        showToast(`Активовано: ${m.n}!`);upB();updateScore();updateStats();    });},{passive:true});multipliersContainer.appendChild(b);m.up=upB;upB();});

// === ВИПРАВЛЕНА СИСТЕМА КЛІКІВ ===
function addTime(){const g=Math.round(clickPower*clickMultiplier*prestigeMultiplier);score+=g;clickCloudTotal+=g;if(g>maxPerClick)maxPerClick=g;clickGainEl.textContent=`+${formatTime(g)}`;showFloating(`+${formatTime(g)}`);triggerClickEffect();handleClickCombo(); updateScore();updatePrestigeProgress();}
function handleClickCombo(){const n=Date.now();if(n-lastClickTime<MAX_CLICK_INTERVAL)currentCombo++;else currentCombo=1;lastClickTime=n;if(currentCombo>maxComboEver)maxComboEver=currentCombo;if(currentCombo>=COMBO_THRESHOLD){comboCount.textContent=currentCombo;comboBubble.classList.add("show");}clearTimeout(comboTimeout);comboTimeout=setTimeout(()=>{if(currentCombo>=COMBO_THRESHOLD){comboBubble.classList.add("burst");showToast(`Комбо ×${currentCombo}! 🔥`);setTimeout(()=>comboBubble.classList.remove("show","burst"),700);}currentCombo=0;},300);}
function showToast(t){const e=d.createElement("div");e.className="toast";e.textContent=t;e.style.cssText="font-size:18px;padding:22px 48px";toastContainer.appendChild(e);setTimeout(()=>e.remove(),10000);}
function triggerClickEffect(){clock.classList.remove("click-effect-red","click-effect-blue","click-effect-glitch","click-effect-blackhole","click-effect-ripple");void clock.offsetWidth;clock.classList.add("click-effect-"+current.effect);}
// ВИПРАВЛЕНИЙ ОБРОБНИК КЛІКІВ - запобігає подвійним клікам
let lastClick=0;clockWrapper.addEventListener("click",e=>{const now=Date.now();if(now-lastClick<100)return;lastClick=now;if(e.target.closest("#clickableClock")||e.target===clockWrapper)addTime();});
function showFloating(t){const e=d.createElement("div");e.textContent=t;e.style.cssText="position:absolute;right:20px;top:50px;color:#ffccd1;font-weight:700;opacity:1;transition:all 0.9s ease-out";clockWrapper.appendChild(e);requestAnimationFrame(()=>{e.style.transform="translateX(60px) translateY(-80px)";e.style.opacity="0";});setTimeout(()=>e.remove(),920);}

// === ВИПРАВЛЕНА СТАТИСТИКА - БЕЗ ЗАТРИМОК ДЛЯ ПК ===
function updateScore(){scoreText.textContent=`Часу витрачено: ${formatTime(score)}`;cloudTotalEl.textContent=`${formatTime(clickCloudTotal)}`;updateAllButtons();}                    
function updateStats(){realTimePlayedEl.textContent=formatTime((Date.now()-sessionStart)/1000);virtualTimeEl.textContent=formatTime(score);totalUpgradesEl.textContent=totalUpgradesBought;maxPerClickEl.textContent=formatTime(maxPerClick);prestigeMultEl.textContent=prestigeMultiplier.toFixed(2);id("maxAutoRate").textContent=formatTime(autoRate);id("maxCombo").textContent=maxComboEver;id("totalReverbs").textContent=totalReverbs;const a=achievementsList.filter(x=>x.done).length;id("achievedCount").textContent=a;id("totalAchievements").textContent=achievementsList.length;id("shapeSkinsCount").textContent=ownedSkins.shapes.length;id("clockSkinsCount").textContent=ownedSkins.clockSkins.length;id("handSkinsCount").textContent=ownedSkins.handSkins.length;id("effectSkinsCount").textContent=ownedSkins.effects.length;id("totalSkins").textContent=ownedSkins.shapes.length+ownedSkins.clockSkins.length+ownedSkins.handSkins.length+ownedSkins.effects.length;updateReverbText(); updatePrestigeProgress();}                    
setInterval(()=>{if(autoRate>maxAutoRate)maxAutoRate=autoRate;if(maxComboEver>maxCombo)maxCombo=maxComboEver;},1000);

// === ДОСЯГНЕННЯ ===
const achRoot=id("achievements"),achievementsList=[{t:"Перший клік",desc:"Зробити перший клік",tg:1,g:()=>clickCloudTotal,done:false},{t:"100 сек",desc:"Витратити 100 сек",tg:100,g:()=>score,done:false},{t:"Перша покупка",desc:"Купити перший апгрейд",tg:1,g:()=>totalUpgradesBought,done:false},{t:"Авто запущено",desc:"Витрачаєш час автоматично",tg:1,g:()=>autoRate>0?1:0,done:false},{t:"Комбо-майстер",desc:"Досягти комбо 10+",tg:10,g:()=>maxComboEver,done:false},{t:"Майстер форм",desc:"Володіти 3 формами годинника",tg:3,g:()=>ownedSkins.shapes.length,done:false},{t:"Господар рамок",desc:"Володіти 3 кольорами рамки",tg:3,g:()=>ownedSkins.clockSkins.length,done:false},{t:"Колекціонер стрілок",desc:"Володіти 3 скінами стрілок",tg:3,g:()=>ownedSkins.handSkins.length,done:false},{t:"Маг ефектів",desc:"Володіти 3 ефектами кліку",tg:3,g:()=>ownedSkins.effects.length,done:false},{t:"Стильний",desc:"Змінити будь-який скін",tg:1,g:()=>(current.shape!=="round"||current.clock!=="neon-blue"||current.hand!=="darkblue"||current.effect!=="red")?1:0,done:false}];
achievementsList.forEach(a=>{const e=d.createElement("div");e.className="achievement";e.innerHTML=`<strong>${a.t}</strong><div style="font-size:12px;color:#bcd">${a.desc}</div><div class="ach-progress"></div><div class="ach-state">0%</div>`;achRoot.appendChild(e);a.p=e.querySelector(".ach-progress");a.s=e.querySelector(".ach-state");});
function updateAchievements(){achievementsList.forEach(a=>{const v=a.g(),p=Math.min(100,(v/a.tg)*100);a.p.style.width=p+"%";if(p>=100&&!a.done){a.done=true;a.s.textContent="Виконано ✅";a.s.style.color="#8df299";showToast(`Досягнення: ${a.t} ✅`);}else if(p<100)a.s.textContent=Math.floor(p)+"%";});}
// === СИСТЕМА ПЕРЕЗАПУСКУ З ПРОГРЕСОМ ===
function updatePrestigeProgress() { currentPrestigeProgress = score; const pB = id('prestigeProgressBar'), pT = id('prestigeProgressText'), pP = Math.min(100, (currentPrestigeProgress / prestigeThreshold) * 100);
    if(pB) { pB.style.width = pP + '%'; pB.style.background = pP >= 100 ? 'linear-gradient(90deg, #10b981, #34d399)' : pP >= 50 ? 'linear-gradient(90deg, #f59e0b, #fbbf24)' : 'linear-gradient(90deg, #ef4444, #f87171)'; }
    if(pT) pT.textContent = `${formatTime(currentPrestigeProgress)} / ${formatTime(prestigeThreshold)}`; updateReverbButtonState(); }
function updateReverbButtonState() { const c = currentPrestigeProgress >= prestigeThreshold;
    reverbBtn.disabled = !c; reverbBtn.style.opacity = c ? '1' : '0.6'; reverbBtn.style.cursor = c ? 'pointer' : 'not-allowed'; reverbBtn.style.background = c ? 'linear-gradient(90deg, #10b981, #34d399)' : 'linear-gradient(90deg, #6b7280, #9ca3af)'; }
function updateReverbText() { nextMultiplierEl.textContent = (prestigeMultiplier * 1.2).toFixed(2); const rD = id('reverbDesc'); if(rD) rD.textContent = `Потрібно для перезапуску: ${formatTime(prestigeThreshold)}`;}
  
// === СКІНИ ===
const clockSkins=[{id:"neon-blue",n:"Неон синій",p:0,a:()=>qa('.clock').forEach(c=>{c.style.borderColor="#0ea5e9";c.style.boxShadow="0 0 50px #0ea5e9, 0 0 100px #0ea5e9"})},{id:"purple",n:"Пурпурний",p:64800,a:()=>qa('.clock').forEach(c=>{c.style.borderColor="#8b5cf6";c.style.boxShadow="0 0 50px #8b5cf6, 0 0 100px #8b5cf6"})},{id:"pink",n:"Рожевий",p:129600,a:()=>qa('.clock').forEach(c=>{c.style.borderColor="#ec4899";c.style.boxShadow="0 0 50px #ec4899, 0 0 100px #ec4899"})},{id:"black",n:"Чорний",p:259200,a:()=>qa('.clock').forEach(c=>{c.style.borderColor="#111";c.style.boxShadow="0 0 10px #000"})}],shapes=[{id:"round",n:"Круг",p:0},{id:"square",n:"Квадрат",p:28800},{id:"diamond",n:"Ромб",p:86400},{id:"oval",n:"Овал",p:172800}],handSkins=[{id:"darkblue",n:"Темно-сині",p:0,a:()=>qa(".hand:not(.second)").forEach(h=>{h.style.background="#1e3a8a";h.style.boxShadow="";h.style.animation="none"})},{id:"pixel",n:"Піксельні",p:900,a:()=>qa(".hand:not(.second)").forEach(h=>{h.style.background="linear-gradient(#fff,#aaa)";h.style.boxShadow="";h.style.animation="none"})},{id:"neon",n:"Неонові",p:9000,a:()=>qa(".hand:not(.second)").forEach(h=>{h.style.background="#0ea5e9";h.style.boxShadow="0 0 25px #0ea5e9, 0 0 60px #0ea5e9";h.style.animation="neonPulse 2s ease-in-out infinite alternate"})},{id:"chrome",n:"Хром",p:43200,a:()=>qa(".hand:not(.second)").forEach(h=>{h.style.background="linear-gradient(90deg,#ddd,#888,#ddd)";h.style.boxShadow="0 0 15px #fff, 0 0 30px #aaa";h.style.animation="none"})}],effects=[{id:"red",n:"Червоний спалах",p:0},{id:"blue",n:"Синій вибух",p:21600},{id:"glitch",n:"Глітч",p:108000},{id:"blackhole",n:"Чорна діра",p:360000},{id:"ripple",n:"Хвиля часу",p:720000}],ownedSkins={shapes:["round"],clockSkins:["neon-blue"],handSkins:["darkblue"],effects:["red"]},current={shape:"round",clock:"neon-blue",hand:"darkblue",effect:"red"};
function buySkin(t,i,p,n){if(ownedSkins[t].includes(i)){current[t==="shapes"?"shape":t==="clockSkins"?"clock":t==="handSkins"?"hand":"effect"]=i;applyAllSkins();refreshAllSkinGrids();return showToast("Скін застосовано! ✅")}if(score<p)return showToast("Не вистачає часу!");score-=p;ownedSkins[t].push(i);current[t==="shapes"?"shape":t==="clockSkins"?"clock":t==="handSkins"?"hand":"effect"]=i;applyAllSkins();updateScore();updateStats();updateAchievements(); updatePrestigeProgress(); showToast(`Куплено: ${n} ✅`);refreshAllSkinGrids()}
function applyAllSkins(){qa('.clock').forEach(c=>c.className="clock "+current.shape);clockSkins.find(s=>s.id===current.clock)?.a();handSkins.find(s=>s.id===current.hand)?.a()}
function createSkinGrid(ct,ls,t){const r=id(ct);r.innerHTML="";ls.forEach(s=>{const e=d.createElement("div");e.className="skin";e.textContent=s.n;const o=ownedSkins[t].includes(s.id);const a=current[t==="shapes"?"shape":t==="clockSkins"?"clock":t==="handSkins"?"hand":"effect"]===s.id;if(o){e.classList.add("owned");if(a)e.classList.add("active");e.onclick=()=>{current[t==="shapes"?"shape":t==="clockSkins"?"clock":t==="handSkins"?"hand":"effect"]=s.id;applyAllSkins();refreshAllSkinGrids();showToast("Скін застосовано! ✅")}}else{e.style.opacity="0.4";if(score>=s.p){e.style.opacity="1";e.style.boxShadow="0 0 15px #0ff"}e.innerHTML+=`<br><small style="color:#ff00ff">${formatTime(s.p)}</small>`;e.onclick=()=>buySkin(t,s.id,s.p,s.n)}r.appendChild(e)})}
function refreshAllSkinGrids(){createSkinGrid("shapeSkins",shapes,"shapes");createSkinGrid("clockSkins",clockSkins,"clockSkins");createSkinGrid("handSkins",handSkins,"handSkins");createSkinGrid("effectSkins",effects,"effects")}
function updateSkinHighlights(){[{l:shapes,t:"shapes",c:"shapeSkins"},{l:clockSkins,t:"clockSkins",c:"clockSkins"},{l:handSkins,t:"handSkins",c:"handSkins"},{l:effects,t:"effects",c:"effectSkins"}].forEach(obj=>{const ct=id(obj.c);if(!ct)return;Array.from(ct.children).forEach((el,i)=>{const s=obj.l[i],o=ownedSkins[obj.t].includes(s.id);if(!o){if(score>=s.p){el.style.opacity="1";el.style.boxShadow="0 0 15px #0ff"}else{el.style.opacity="0.4";el.style.boxShadow=""}el.innerHTML=s.n+`<br><small style="color:#ff00ff">${formatTime(s.p)}</small>`}else{el.style.opacity="1";el.style.boxShadow="";el.innerHTML=s.n}})})}
setInterval(updateSkinHighlights,50);refreshAllSkinGrids();applyAllSkins();

// === АВТОМАТИЧНИЙ ПРИБУТОК ===
setInterval(()=>{const g=Math.round(autoRate*prestigeMultiplier);if(g>0){score+=g;clickCloudTotal+=g;updateScore();}updateStats();updateAchievements();},1000);

// === ГОДИННИК ===
function updateClockHands(){
const n=new Date(),s=n.getSeconds()+n.getMilliseconds()/1000,m=n.getMinutes()+s/60,h=(n.getHours()%12||12)+m/60; qa("#clickableClock .second").forEach(x=>x.style.transform=`translateX(-50%) rotate(${s*6}deg)`);qa("#clickableClock .minute").forEach(x=>x.style.transform=`translateX(-50%) rotate(${m*6}deg)`); qa("#clickableClock .hour").forEach(x=>x.style.transform=`translateX(-50%) rotate(${h*30}deg)`);}
setInterval(updateClockHands,50);updateClockHands();

// === СИСТЕМА ЕФЕКТУ ПЕРЕЗАПУСКУ ===
const restartEffect={active:!1,clocksInt:null,bubblesInt:null,
init(){const e=document.createElement("div");e.id="restartEffectOverlay";e.style.cssText="position:fixed;top:0;left:0;width:100%;height:100%;z-index:10000;display:none;pointer-events:none;background:transparent;";document.body.appendChild(e);this.clocksContainer=document.createElement("div");this.clocksContainer.style.cssText="position:absolute;top:0;left:0;width:100%;height:100%;pointer-events:none;";this.bubblesContainer=document.createElement("div");this.bubblesContainer.style.cssText="position:absolute;top:0;left:0;width:100%;height:100%;pointer-events:none;";e.appendChild(this.clocksContainer);e.appendChild(this.bubblesContainer);
// ОКРЕМИЙ екран завершення
this.completionScreen=document.createElement("div");this.completionScreen.id="reverbCompletionScreen";this.completionScreen.style.cssText="position:fixed;top:0;left:0;width:100%;height:100%;background:#000;z-index:10002;display:none;align-items:center;justify-content:center;flex-direction:column;color:white;font-family:Poppins;text-align:center;";this.completionScreen.innerHTML=`<div style="font-size:32px;margin-bottom:20px;text-shadow:0 0 20px #0ea5e9">Ви успішно повернулися в часі!</div><div style="font-size:24px;margin-bottom:20px">Ваш множник: ${prestigeMultiplier.toFixed(2)}×</div><div style="font-size:18px;color:#cfeaff">Натисніть будь-де щоб продовжити</div>`;document.body.appendChild(this.completionScreen);},
start(){this.active=!0;document.getElementById("restartEffectOverlay").style.display="block";this.clocksContainer.innerHTML="";this.bubblesContainer.innerHTML="";this.clocksInt=setInterval(()=>this.createFlyingClock(),300);this.bubblesInt=setInterval(()=>this.createStatBubble(),1200)},
stop(){this.active=!1;clearInterval(this.clocksInt);clearInterval(this.bubblesInt);document.getElementById("restartEffectOverlay").style.display="none"},
showCompletionScreen(){ reverbOverlay.classList.add("hidden");document.getElementById("restartEffectOverlay").style.display="none";timeTunnel.classList.remove("active","intense");this.completionScreen.style.display="flex";},
hideCompletionScreen(){this.completionScreen.style.display="none"},
createFlyingClock(){const e=document.createElement("div");e.className="flying-clock";const t=80+100*Math.random();e.style.width=e.style.height=t+"px";e.style.left=Math.random()*100+"%";e.style.top=Math.random()*100+"%";e.style.animationDuration=4+6*Math.random()+"s";e.style.animationDelay=0.5*Math.random()+"s";Math.random()>0.5&&(e.style.transform="scaleX(-1)");this.clocksContainer.appendChild(e);setTimeout(()=>{e.parentNode&&e.parentNode.removeChild(e)},1e4)},
createStatBubble(){const e=document.createElement("div");e.className="stat-bubble";const t=[`Максимальне комбо: ${maxComboEver||0}`,`Витрачено часу: ${formatTime(clickCloudTotal)}`,`Ревербів: ${totalReverbs}`,`Всього скінів: ${(ownedSkins.shapes.length+ownedSkins.clockSkins.length+ownedSkins.handSkins.length+ownedSkins.effects.length)||0}`,`Авточас/сек: ${formatTime(autoRate)}`,`Макс за клік: ${formatTime(maxPerClick)}`,`Досягнень: ${(achievementsList.filter(e=>e.done).length)}/${achievementsList.length}`];e.textContent=t[Math.floor(Math.random()*t.length)];e.style.left=10+80*Math.random()+"%";e.style.top=20+60*Math.random()+"%";this.bubblesContainer.appendChild(e);setTimeout(()=>{e.parentNode&&e.parentNode.removeChild(e)},4e3)}};
restartEffect.init();
  
// === РЕВЕРБ СИСТЕМА ===
reverbBtn.addEventListener("click",()=>{if(!confirm("Ти впевнений, що хочеш повернути час назад? Всі твої апгрейди будуть втрачені, але ти отримаєш множник!"))return;startReverbMode();});
function startReverbMode(){    reverbOverlay.classList.remove("hidden");timeTunnel.classList.add("active");reverbHint.style.opacity="1";isReverbActive=1;    reverbClock.className=`clock ${current.shape}`;clockSkins.find(s=>s.id===current.clock)?.a();handSkins.find(s=>s.id===current.hand)?.a();    updateReverbClockHands();setTimeout(()=>reverbHint.style.opacity="0",3000);}
function updateReverbClockHands(){    if(!isReverbActive)return;const e=qa("#reverbClock .hand");if(e.length===0)return;    if(reverbClock.classList.contains("reverb-chaos")){requestAnimationFrame(updateReverbClockHands);return;}    const t=new Date(),o=t.getSeconds()+t.getMilliseconds()/1000,n=t.getMinutes()+o/60,a=(t.getHours()%12||12)+n/60;    qa("#reverbClock .second").forEach(e=>e.style.transform=`translateX(-50%) rotate(${o*6}deg)`);    qa("#reverbClock .minute").forEach(e=>e.style.transform=`translateX(-50%) rotate(${n*6}deg)`);    qa("#reverbClock .hour").forEach(e=>e.style.transform=`translateX(-50%) rotate(${a*30}deg)`);    requestAnimationFrame(updateReverbClockHands);}
const startReverbHold=e=>{    if(e.type.includes('touch'))e.preventDefault();if(!isReverbActive)return;    reverbHint.style.opacity="0";reverbClock.classList.add("reverb-mode","reverb-chaos");timeTunnel.classList.add("intense");    restartEffect.start();
    qa("#reverbClock .hand").forEach((e,t)=>{        const o=0.5+2*Math.random(),n=Math.random()>0.5?"normal":"reverse";        e.style.setProperty("--duration",`${o}s`);e.style.setProperty("--direction",n);        e.style.animation=`chaosSpin ${o}s linear infinite ${n}`;    });reverbHoldTimeout=setTimeout(completeReverb,10000);};
const stopReverbHold=e=>{    if(e&&e.type.includes('touch'))e.preventDefault();    clearTimeout(reverbHoldTimeout);    if(isReverbActive){        reverbClock.classList.remove("reverb-mode","reverb-chaos");timeTunnel.classList.remove("intense");        qa("#reverbClock .hand").forEach(e=>{e.style.animation="none";e.style.removeProperty("--duration");e.style.removeProperty("--direction");});        updateReverbClockHands();restartEffect.stop();}};
reverbClock.addEventListener("mousedown",startReverbHold);reverbClock.addEventListener("touchstart",startReverbHold,{passive:false});
reverbClock.addEventListener("mouseup",stopReverbHold);reverbClock.addEventListener("mouseleave",stopReverbHold);
reverbClock.addEventListener("touchend",stopReverbHold);reverbClock.addEventListener("touchcancel",stopReverbHold);
function completeReverb() {
    if (currentPrestigeProgress < prestigeThreshold) { showToast(`Потрібно ще ${formatTime(prestigeThreshold - currentPrestigeProgress)}!`); return; }
    stopReverbHold(new Event('manual')); prestigeThreshold += 7200; prestigeMultiplier *= 1.2; totalReverbs++;
    currentPrestigeProgress = score = clickCloudTotal = currentCombo = 0; clickPower = maxPerClick = 1; autoRate = totalUpgradesBought = 0;
    upgrades.forEach((e,t) => { e.l = 0; if(buttons[t]) buttons[t].classList[t?"add":"remove"]("hidden"); e.up(); });
    multipliers.forEach(e => { if(e.b) { e.b = 0; clickMultiplier = 1; } e.up?.(); });
    const e = document.createElement("div"); e.style.cssText = "position:fixed;top:0;left:0;width:100%;height:100%;background:white;z-index:10001;pointer-events:none;animation:flashFade 1s ease-out forwards;"; document.body.appendChild(e);
    setTimeout(() => { e.remove(); restartEffect.showCompletionScreen(); restartEffect.completionScreen.querySelector("div:nth-child(2)").textContent = `Множник: ${prestigeMultiplier.toFixed(2)}×`; updateReverbText();
        const o = () => { restartEffect.hideCompletionScreen(); isReverbActive = 0; updateScore(); updateStats(); updateAchievements(); updatePrestigeProgress(); document.removeEventListener('click',o); document.removeEventListener('touchstart',o); };
        document.addEventListener('click',o); document.addEventListener('touchstart',o);    }, 1000);}
  
// === СИСТЕМА ВКЛАДОК ===
qa(".top-tabs .tab").forEach(b=>{b.addEventListener("click",()=>{qa(".top-tabs .tab").forEach(x=>x.classList.remove("active"));qa(".tab-page").forEach(x=>x.classList.remove("active"));b.classList.add("active");id(b.dataset.tab).classList.add("active");});});

// === СЕКРЕТНА СИСТЕМА ===
if(worldTitle){worldTitle.addEventListener("keydown",e=>{if(e.key==="Enter")e.preventDefault();});const normalizeTitle=()=>{let t=worldTitle.textContent.trim();if(!t)worldTitle.textContent="Times Clicker";else if(!/\sTime$/i.test(t))worldTitle.textContent=`${t} Time`;};let titleCheckTimeout=null;const checkTitleForSecret=()=>{const t=worldTitle.textContent.trim().replace(/\s+/g,'');if(/^22092005$/i.test(t)){if(!id("ultimateDevPanel")){showToast("22.09.2005 — доступ відкрито через назву!");createDevPanel();}if(titleCheckTimeout)clearTimeout(titleCheckTimeout);titleCheckTimeout=null;return;}clearTimeout(titleCheckTimeout);titleCheckTimeout=setTimeout(checkTitleForSecret,800);};worldTitle.addEventListener("blur",()=>{normalizeTitle();checkTitleForSecret();});checkTitleForSecret();}
let secretCode="",magicCode="22092005";d.addEventListener("keydown",e=>{secretCode+=e.key;if(secretCode.length>8)secretCode=secretCode.slice(-8);if(secretCode===magicCode){secretCode="";showToast("22.09.2005 — доступ відкрито!");createDevPanel();}});
function createDevPanel(){if(id("ultimateDevPanel"))return;const p=d.createElement("div");p.id="ultimateDevPanel";p.style.cssText="position:fixed;bottom:20px;left:20px;z-index:99999;background:rgba(0,0,0,0.9);backdrop-filter:blur(12px);border:2px solid #ff00ff;border-radius:14px;padding:12px 16px;box-shadow:0 0 30px #ff00ff;font-family:Poppins,sans-serif;color:#fff;font-size:13px;width:210px;";p.innerHTML='<div style="color:#ff00ff;font-weight:700;text-align:center;margin-bottom:8px;font-size:14px;">Секретна панель</div>';function addBtn(t,c,a){const b=d.createElement("button");b.textContent=t;b.style.cssText="margin:4px 0;padding:8px 12px;width:100%;background:"+c+";border:none;border-radius:10px;color:#fff;font-weight:600;cursor:pointer;font-size:12px;transition:transform 0.2s;";b.onmouseover=()=>b.style.transform="translateY(-2px)";b.onmouseout=()=>b.style.transform="";b.onclick=()=>{a();showToast(t+" OK");};p.appendChild(b);}addBtn("+10 години","#06d6d6",()=>{score+=36000;clickCloudTotal+=36000;updateScore();updateStats();});addBtn("+100 авто/сек","#3b82f6",()=>autoRate+=100);addBtn("×2 престиж","#a855f7",()=>{prestigeMultiplier*=2;updateStats();});addBtn("Реверб","#ec4899",()=>completeReverb());addBtn("Закрити","#555",()=>{p.remove();showToast("Панель закрита");});d.body.appendChild(p);}

// === СИСТЕМА ЕКРАНІВ БЛОКУВАННЯ ТЕЛЕФОНУ ===
let phoneLockImages=['photoList/1.jpg','photoList/2.jpg','photoList/3.jpg','photoList/4.jpg','photoList/5.jpg','photoList/6.jpg','photoList/7.jpg','photoList/8.jpg','photoList/9.jpg','photoList/10.jpg'];let phoneSwipe={startY:0,endY:0,isSwiping:false,hintTimeout:null};function showPhoneLockScreen(){const randomIndex=Math.floor(Math.random()*phoneLockImages.length);const lockImage=document.getElementById('phoneLockImage');lockImage.src=phoneLockImages[randomIndex];const overlay=document.getElementById('phoneLockOverlay');overlay.style.display='flex';phoneSwipe.startY=0;phoneSwipe.endY=0;phoneSwipe.isSwiping=false;phoneSwipe.hintTimeout=setTimeout(()=>{document.getElementById('swipeHint').classList.add('show');},10000);setupPhoneSwipeListeners();}
function hidePhoneLockScreen(){const overlay=document.getElementById('phoneLockOverlay');overlay.style.display='none';document.getElementById('swipeHint').classList.remove('show');if(phoneSwipe.hintTimeout){clearTimeout(phoneSwipe.hintTimeout);phoneSwipe.hintTimeout=null;}removePhoneSwipeListeners();}
function setupPhoneSwipeListeners(){const lockScreen=document.getElementById('phoneLockScreen');lockScreen.addEventListener('mousedown',handleSwipeStart);lockScreen.addEventListener('mousemove',handleSwipeMove);lockScreen.addEventListener('mouseup',handleSwipeEnd);lockScreen.addEventListener('mouseleave',handleSwipeCancel);lockScreen.addEventListener('touchstart',handleSwipeStart,{passive:false});lockScreen.addEventListener('touchmove',handleSwipeMove,{passive:false});lockScreen.addEventListener('touchend',handleSwipeEnd);lockScreen.addEventListener('touchcancel',handleSwipeCancel);}
function removePhoneSwipeListeners(){const lockScreen=document.getElementById('phoneLockScreen');lockScreen.removeEventListener('mousedown',handleSwipeStart);lockScreen.removeEventListener('mousemove',handleSwipeMove);lockScreen.removeEventListener('mouseup',handleSwipeEnd);lockScreen.removeEventListener('mouseleave',handleSwipeCancel);lockScreen.removeEventListener('touchstart',handleSwipeStart);lockScreen.removeEventListener('touchmove',handleSwipeMove);lockScreen.removeEventListener('touchend',handleSwipeEnd);lockScreen.removeEventListener('touchcancel',handleSwipeCancel);}
function handleSwipeStart(e){phoneSwipe.isSwiping=true;phoneSwipe.startY=e.clientY||e.touches[0].clientY;document.getElementById('swipeHint').classList.remove('show');}
function handleSwipeMove(e){if(!phoneSwipe.isSwiping)return;e.preventDefault();phoneSwipe.endY=e.clientY||e.touches[0].clientY;const deltaY=phoneSwipe.startY-phoneSwipe.endY;if(deltaY>100){handleSuccessfulUnlock();}}
function handleSwipeEnd(){phoneSwipe.isSwiping=false;}
function handleSwipeCancel(){phoneSwipe.isSwiping=false;}
function handleSuccessfulUnlock(){hidePhoneLockScreen();const notification=document.getElementById('phoneUnlockNotification');notification.classList.add('show');setTimeout(()=>{notification.classList.remove('show');},3000);score+=500;clickCloudTotal+=500;updateScore();}
  
// === RSS СИСТЕМА ===
const rssFeeds=['https://www.ukrinform.ua/rss','https://www.pravda.com.ua/rss/','https://interfax.com.ua/news/general.rss','https://tsn.ua/rss','https://www.bbc.com/ukrainian/index.xml'];let cachedNews=[],lastFetchTime=0,shownNewsUrls=new Set(),newsTickerVisible=false;const CACHE_DURATION=30*60*1000;
async function fetchRSSNews(){if(cachedNews.length>0&&Date.now()-lastFetchTime<CACHE_DURATION)return cachedNews;try{const proxyUrl='https://api.allorigins.win/raw?url=';const randomFeed=rssFeeds[Math.floor(Math.random()*rssFeeds.length)];const response=await fetch(`${proxyUrl}${encodeURIComponent(randomFeed)}`,{mode:'cors'}).catch(()=>null);if(!response)return[];const text=await response.text();const parser=new DOMParser();const xmlDoc=parser.parseFromString(text,'text/xml');const items=xmlDoc.querySelectorAll('item');const news=[];items.forEach(item=>{const title=item.querySelector('title')?.textContent||'';const description=item.querySelector('description')?.textContent||'';const link=item.querySelector('link')?.textContent||'';const pubDate=item.querySelector('pubDate')?.textContent||'';if(title&&description){const cleanDescription=description.replace(/<[^>]*>/g,'').substring(0,150);news.push({title:title.substring(0,80),text:cleanDescription+'...',source:'Укрінформ',date:pubDate,link:link});}});cachedNews=news.slice(0,20);lastFetchTime=Date.now();return cachedNews;}catch(e){console.error('RSS error:',e);return[];}}
function getSourceName(url){const sources={'ukrinform.ua':'Укрінформ','pravda.com.ua':'УП','interfax.com.ua':'Інтерфакс','tsn.ua':'ТСН','bbc.com':'BBC'};for(const[key,value]of Object.entries(sources))if(url.includes(key))return value;return 'Новини';}
async function addNewsToTicker(){try{const news=await fetchRSSNews();if(!news||news.length===0){showToast('Не знайдено новин 😔');return;}let availableNews=[];for(const item of news){if(!shownNewsUrls.has(item.link)&&item.title&&item.text){availableNews.push(item);if(availableNews.length>=3)break;}}if(availableNews.length===0){shownNewsUrls.clear();availableNews=news.slice(0,3);}const selected=availableNews[Math.floor(Math.random()*availableNews.length)];shownNewsUrls.add(selected.link);const newsTicker=document.getElementById('newsTicker');const newsItem=document.createElement('div');newsItem.className='news-item';let dateStr='';if(selected.date){try{const date=new Date(selected.date);dateStr=date.toLocaleTimeString('uk-UA',{hour:'2-digit',minute:'2-digit',hour12:false});}catch(e){dateStr='сьогодні';}}newsItem.innerHTML=`<div class="news-ticker-header"><span class="news-source">${selected.source||'Новини'}</span>${dateStr?`<span class="news-time">${dateStr}</span>`:''}</div><div class="news-ticker-title">${selected.title}</div><div class="news-ticker-text">${selected.text}</div>`;if(selected.link){newsItem.style.cursor='pointer';newsItem.addEventListener('click',()=>{window.open(selected.link,'_blank');});}newsTicker.appendChild(newsItem);setTimeout(()=>{newsTicker.scrollTop=newsTicker.scrollHeight;},100);const allNews=newsTicker.querySelectorAll('.news-item');if(allNews.length>5)allNews[0].remove();if(!newsTickerVisible)showNewsTicker();}catch(error){console.error('News error:',error);showToast('Помилка завантаження новин');}}
function showNewsTicker(){const container=document.getElementById('newsTickerContainer');if(container){container.classList.add('show');newsTickerVisible=true;setTimeout(()=>{if(newsTickerVisible)hideNewsTicker();},30000);}}
function hideNewsTicker(){const container=document.getElementById('newsTickerContainer');if(container){container.classList.remove('show');newsTickerVisible=false;}}
function handleNewsFeedUpgrade(){addNewsToTicker();showToast('Нова новина в стрічці! 📰');}

// === СИСТЕМА МЕМ-ТУРУ ===
let memeImages=['https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif','https://media.giphy.com/media/3o7abAHdYvZdBNnGZq/giphy.gif','https://media.giphy.com/media/26ufdipQqU2lhNA4g/giphy.gif','https://media.giphy.com/media/11sBLVxNs7v6WA/giphy.gif','https://media.giphy.com/media/jUwpNzg9IcyrK/giphy.gif','https://media.giphy.com/media/l46Cy1rHbQ92uuLXa/giphy.gif','https://media.giphy.com/media/YQitE4YNQNahy/giphy.gif','https://media.giphy.com/media/l3q2K5jinAlChoCLS/giphy.gif','https://media.giphy.com/media/3o7abBbea7eQz6qJp6/giphy.gif','https://media.giphy.com/media/26tknCqiJrBQG6DrC/giphy.gif'];
let memeOverlay=null,memeImageEl=null,currentMemeTimeout=null,memeLoadingEl=null,isMemeShowing=false;
function initMemeSystem(){memeOverlay=document.createElement('div');memeOverlay.id='memeOverlay';memeOverlay.style.cssText='position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.95);z-index:9998;display:none;align-items:center;justify-content:center;flex-direction:column;';
memeLoadingEl=document.createElement('div');memeLoadingEl.id='memeLoading';memeLoadingEl.textContent='Завантаження мему...';memeLoadingEl.style.cssText='color:white;font-size:18px;margin-bottom:20px;display:none;';
memeImageEl=document.createElement('img');memeImageEl.id='memeImage';memeImageEl.style.cssText='max-width:85%;max-height:70%;border-radius:15px;box-shadow:0 0 50px rgba(255,255,255,0.4);object-fit:contain;display:none;';
const memeText=document.createElement('div');memeText.textContent='Мем-тур активовано!';memeText.style.cssText='color:#ffcc00;font-size:20px;margin-top:20px;text-shadow:0 0 10px #ffcc00;';
const closeBtn=document.createElement('button');closeBtn.textContent='Закрити (або чекай 7 сек)';closeBtn.style.cssText='margin-top:25px;padding:10px 25px;background:#ef4444;color:white;border:none;border-radius:10px;font-size:16px;cursor:pointer;font-weight:bold;';closeBtn.onclick=hideMeme;
memeOverlay.appendChild(memeLoadingEl);memeOverlay.appendChild(memeImageEl);memeOverlay.appendChild(memeText);memeOverlay.appendChild(closeBtn);document.body.appendChild(memeOverlay);
memeOverlay.addEventListener('click',function(e){if(e.target===memeOverlay)hideMeme();});
memeImageEl.onload=function(){memeLoadingEl.style.display='none';memeImageEl.style.display='block';clearTimeout(currentMemeTimeout);currentMemeTimeout=setTimeout(hideMeme,7000);};
memeImageEl.onerror=function(){memeLoadingEl.textContent='Помилка завантаження мему :(';setTimeout(hideMeme,2000);};}
function showMeme(){if(!memeImageEl)initMemeSystem();
if(isMemeShowing){clearTimeout(currentMemeTimeout);memeOverlay.style.display='none';isMemeShowing=false;}
const randomIndex=Math.floor(Math.random()*memeImages.length);const memeUrl=memeImages[randomIndex];
memeLoadingEl.style.display='block';memeImageEl.style.display='none';memeOverlay.style.display='flex';
isMemeShowing=true;
memeImageEl.src=memeUrl;}
function hideMeme(){if(memeOverlay){memeOverlay.style.display='none';}isMemeShowing=false;clearTimeout(currentMemeTimeout);}

// === СИСТЕМА АВТОПЕРЕГЛЯДУ ===
let autoplayOverlay=null,autoplayTimeout=null,autoplayVideos=[{channel:"Улюбленці",views:"1.2M",time:"0:15",thumbnail:"https://picsum.photos/600/340?random=1"},{channel:"Кулінарія",views:"850K",time:"0:30",thumbnail:"https://picsum.photos/600/340?random=2"},{channel:"Танці",views:"2.5M",time:"0:25",thumbnail:"https://picsum.photos/600/340?random=3"},{channel:"Фітнес",views:"950K",time:"0:45",thumbnail:"https://picsum.photos/600/340?random=4"},{channel:"Природа",views:"3.1M",time:"1:10",thumbnail:"https://picsum.photos/600/340?random=5"},{channel:"Автоогляд",views:"1.8M",time:"0:55",thumbnail:"https://picsum.photos/600/340?random=6"},{channel:"Ігри",views:"2.2M",time:"12:30",thumbnail:"https://picsum.photos/600/340?random=7"},{channel:"Кліпи",views:"4.5M",time:"3:45",thumbnail:"https://picsum.photos/600/340?random=8"}];
function showAutoplay(){autoplayOverlay=document.createElement('div');autoplayOverlay.id='autoplayOverlay';autoplayOverlay.style.cssText='position:fixed;top:0;left:0;width:100%;height:100%;background:#0f0f0f;z-index:9997;display:flex;flex-direction:column;font-family:Poppins;color:white;';
const header=document.createElement('div');header.style.cssText='display:flex;align-items:center;padding:15px 20px;border-bottom:1px solid #333;background:#202020;';header.innerHTML='<div style="display:flex;align-items:center;gap:10px;"><div style="width:30px;height:30px;background:#ff0000;border-radius:50%;"></div><span style="font-weight:bold;font-size:20px;">Автоперегляд</span></div>';
const content=document.createElement('div');content.style.cssText='flex:1;display:flex;align-items:center;justify-content:center;padding:20px;';
const currentVideo=autoplayVideos[Math.floor(Math.random()*autoplayVideos.length)];content.innerHTML=`<div style="max-width:600px;width:100%;background:#282828;border-radius:15px;overflow:hidden;"><div style="position:relative;"><img src="${currentVideo.thumbnail}" style="width:100%;height:340px;object-fit:cover;"><div style="position:absolute;bottom:10px;right:10px;background:rgba(0,0,0,0.8);padding:5px 10px;border-radius:5px;">${currentVideo.time}</div><div style="position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);width:70px;height:70px;background:rgba(255,255,255,0.9);border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:30px;">▶️</div></div><div style="padding:20px;"><div style="font-size:22px;font-weight:bold;margin-bottom:10px;">${currentVideo.channel}</div><div style="display:flex;justify-content:space-between;color:#aaa;margin-bottom:20px;"><span>${currentVideo.views} переглядів</span><span>${currentVideo.time}</span></div><div style="background:#3ea6ff;color:white;border:none;padding:12px 25px;border-radius:20px;font-weight:bold;cursor:pointer;text-align:center;margin-bottom:20px;">Підписатися</div><div style="display:flex;gap:15px;color:#aaa;justify-content:center;"><div style="text-align:center;"><div style="font-size:24px;">👍</div><div>1.2K</div></div><div style="text-align:center;"><div style="font-size:24px;">👎</div><div>25</div></div><div style="text-align:center;"><div style="font-size:24px;">💬</div><div>348</div></div><div style="text-align:center;"><div style="font-size:24px;">↪️</div><div>Поділитись</div></div></div></div></div>`;
const sidebar=document.createElement('div');sidebar.style.cssText='width:300px;background:#181818;padding:20px;border-left:1px solid #333;';let recommendations='<div style="font-size:18px;margin-bottom:20px;">Рекомендації:</div>';let shuffled=[...autoplayVideos].filter(v=>v!==currentVideo).sort(()=>0.5-Math.random()).slice(0,4);shuffled.forEach(vid=>{recommendations+=`<div style="display:flex;margin-bottom:15px;background:#282828;border-radius:10px;overflow:hidden;cursor:pointer;"><img src="${vid.thumbnail}" style="width:120px;height:70px;object-fit:cover;"><div style="padding:10px;flex:1;"><div style="font-weight:bold;margin-bottom:5px;">${vid.channel}</div><div style="font-size:13px;color:#aaa;">${vid.views} · ${vid.time}</div></div></div>`;});sidebar.innerHTML=recommendations;
const container=document.createElement('div');container.style.cssText='display:flex;flex:1;';container.appendChild(content);container.appendChild(sidebar);
const timer=document.createElement('div');timer.id='autoplayTimer';timer.style.cssText='position:fixed;bottom:20px;left:20px;background:rgba(0,0,0,0.8);color:#3ea6ff;padding:10px 20px;border-radius:10px;font-size:16px;';timer.textContent='Наступне відео через: 5 сек';
autoplayOverlay.appendChild(header);autoplayOverlay.appendChild(container);autoplayOverlay.appendChild(timer);document.body.appendChild(autoplayOverlay);
let secondsLeft=5;autoplayTimeout=setInterval(()=>{secondsLeft--;timer.textContent=`Наступне відео через: ${secondsLeft} сек`;if(secondsLeft<=0){clearInterval(autoplayTimeout);hideAutoplay();}},1000);}
function hideAutoplay(){if(autoplayOverlay){autoplayOverlay.remove();}clearInterval(autoplayTimeout);score+=1500;clickCloudTotal+=1500;showToast("+1500 сек за автоперегляд! 📺");updateScore();}

// === СИСТЕМА ПІДПИСКИ (ХРЕСТИК + КНОПКА) ===
let subscriptionOverlay=null;const subscriptionServices=[{name:"YouTube Premium",desc:"Музика без реклами",price:"₴199/міс",color:"#FF0000",emoji:"🎬",link:"https://www.youtube.com/premium"},{name:"Spotify",desc:"Мільйони пісень",price:"€9.99/міс",color:"#1DB954",emoji:"🎵",link:"https://www.spotify.com"},{name:"Netflix",desc:"Фільми та серіали",price:"₴239/міс",color:"#E50914",emoji:"🍿",link:"https://www.netflix.com"},{name:"Disney+",desc:"Дитячі та сімейні",price:"₴159/міс",color:"#113CCF",emoji:"🏰",link:"https://www.disneyplus.com"},{name:"Megogo",desc:"Український контент",price:"₴129/міс",color:"#FF6B00",emoji:"🇺🇦",link:"https://megogo.net"},{name:"Sweet.TV",desc:"ТВ онлайн",price:"₴149/міс",color:"#8A2BE2",emoji:"📺",link:"https://sweet.tv"},{name:"Google One",desc:"Місце в хмарі",price:"₴79/міс",color:"#4285F4",emoji:"☁️",link:"https://one.google.com"}];
function showSubscription(){subscriptionOverlay=document.createElement('div');subscriptionOverlay.id='subscriptionOverlay';subscriptionOverlay.style.cssText='position:fixed;top:0;left:0;width:100%;height:100%;z-index:9996;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,0.85);';
const service=subscriptionServices[Math.floor(Math.random()*subscriptionServices.length)];
const container=document.createElement('div');container.style.cssText=`position:relative;max-width:450px;padding:40px;background:${service.color};border-radius:25px;box-shadow:0 25px 70px rgba(0,0,0,0.7);border:5px solid white;`;
const closeBtn=document.createElement('div');closeBtn.style.cssText='position:absolute;top:15px;right:15px;width:30px;height:30px;background:rgba(255,255,255,0.9);border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:20px;font-weight:bold;cursor:pointer;color:#333;';closeBtn.innerHTML='×';closeBtn.onclick=()=>{subscriptionOverlay.style.opacity='0';setTimeout(()=>{if(subscriptionOverlay){subscriptionOverlay.remove();}},300);};
container.appendChild(closeBtn);container.innerHTML+=`<div style="text-align:center;"><div style="font-size:48px;margin-bottom:20px;">${service.emoji}</div><div style="font-size:32px;font-weight:bold;color:white;margin-bottom:15px;">${service.name}</div><div style="font-size:18px;color:rgba(255,255,255,0.95);margin-bottom:25px;background:rgba(255,255,255,0.15);padding:15px;border-radius:15px;">${service.desc}</div><div style="font-size:28px;font-weight:bold;color:white;margin-bottom:30px;background:rgba(0,0,0,0.2);padding:15px 25px;border-radius:15px;display:inline-block;">${service.price}</div><div style="font-size:16px;color:rgba(255,255,255,0.8);margin-bottom:30px;">Ексклюзивна пропозиція!</div><button id="subscribeBtn" style="background:white;color:${service.color};border:none;padding:18px 40px;border-radius:12px;font-size:20px;font-weight:bold;cursor:pointer;transition:all 0.3s;">Підписатися зараз</button></div>`;
subscriptionOverlay.appendChild(container);document.body.appendChild(subscriptionOverlay);
document.getElementById('subscribeBtn').onclick=()=>{if(service.link){window.open(service.link,'_blank');}subscriptionOverlay.style.opacity='0';setTimeout(()=>{if(subscriptionOverlay){subscriptionOverlay.remove();}},300);};
setTimeout(()=>{container.style.transform='scale(1)';container.style.opacity='1';},10);container.style.transform='scale(0.8)';container.style.opacity='0';container.style.transition='all 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275)';}
  // === Динамічний текст Перезапуску ===
const reverbDesc = id("reverbDesc"), nextMultiplierEl = id("nextMultiplier"); function updateReverbText(){nextMultiplierEl.textContent=(prestigeMultiplier*1.2).toFixed(2);}    setTimeout(() => {updateScore();updateStats();updateAchievements();updateReverbText();}, 100);}
